# Generated by Django 5.0 on 2023-12-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0002_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='DNI_estudiante',
        ),
    ]
