# Generated by Django 5.0 on 2023-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0003_remove_estudiante_dni_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=20)),
                ('fecha_entrega', models.DateTimeField()),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(error_messages={'unique': 'El numero de camada que intenta registrar ya existe. \nPor favor, utiliza otro numero.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email_estudiante',
            field=models.EmailField(error_messages={'unique': 'El correo electrónico que intenta ingresar ya se encuentra registrado.\nPor favor, utiliza otro.'}, max_length=254, unique=True),
        ),
    ]
